# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Brendan Cooley
tagline:             'International Relations | Political Economy | Violent Conflict'
description:         'Brendan Cooley'
url:                 http://brendancooley.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Brendan Cooley
  url:               https://brendancooley.github.io
  email:             bcooley@princeton.edu

# Custom vars
version:             1.0.0
